x-service-common: &service-common
  ports:
    - "8189:8188"
    - "8889:8889"
  stdin_open: true
  tty: true
  volumes:
    - /media/tony/Junior/ComfyUI/models:/workspace/ComfyUI/models
    - /media/tony/Junior/ComfyUI/input:/workspace/ComfyUI/input
    - /media/tony/Junior/ComfyUI/output:/workspace/ComfyUI/output
    - /media/tony/Junior/ComfyUI/user/default/workflows:/workspace/ComfyUI/user/default/workflows
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

services:
  main:
    <<: *service-common
    build:
      context: .
      dockerfile: Dockerfile
    image: unity-comfystream:latest

  dev:
    <<: *service-common
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: unity-comfystream:dev
